/* =====================================================================
   Trafik Levhaları (SVG) + Animasyonlu Dersler + Arayüz Metinleri
   ===================================================================== */

/* ---------- SVG levha yardımcıları ---------- */
const SG = {
  // Kırmızı çemberli yasak levhası
  redCircle: (inner) => `<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="47" fill="#fff" stroke="#c00" stroke-width="9"/>${inner}</svg>`,
  // Mavi zorunluluk levhası
  blueCircle: (inner) => `<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="47" fill="#0064c8" stroke="#eee" stroke-width="2"/>${inner}</svg>`,
  // Üçgen uyarı levhası
  triangle: (inner) => `<svg viewBox="0 0 100 100"><path d="M50 6 L96 90 L4 90 Z" fill="#fff" stroke="#c00" stroke-width="8" stroke-linejoin="round"/>${inner}</svg>`,
  // Ters üçgen (yol ver)
  invTriangle: () => `<svg viewBox="0 0 100 100"><path d="M4 15 L96 15 L50 92 Z" fill="#fff" stroke="#c00" stroke-width="8" stroke-linejoin="round"/><text x="50" y="47" font-size="16" font-weight="bold" text-anchor="middle" fill="#333">GIVE</text><text x="50" y="64" font-size="16" font-weight="bold" text-anchor="middle" fill="#333">WAY</text></svg>`,
  // Sekizgen STOP
  stop: () => `<svg viewBox="0 0 100 100"><path d="M30 5 H70 L95 30 V70 L70 95 H30 L5 70 V30 Z" fill="#c00" stroke="#fff" stroke-width="4"/><text x="50" y="60" font-size="26" font-weight="bold" text-anchor="middle" fill="#fff">STOP</text></svg>`,
  // Mavi dikdörtgen bilgi
  blueRect: (inner) => `<svg viewBox="0 0 100 100"><rect x="4" y="4" width="92" height="92" rx="8" fill="#0064c8"/>${inner}</svg>`,
  car: (x, y, s, c) => `<g transform="translate(${x},${y}) scale(${s})"><rect x="0" y="6" width="30" height="10" rx="3" fill="${c}"/><path d="M6 6 L10 0 H21 L25 6 Z" fill="${c}"/><circle cx="8" cy="17" r="3.4" fill="#222"/><circle cx="23" cy="17" r="3.4" fill="#222"/></g>`,
};

const SIGNS = [
  { id: "s20zone",   cat: "order", svg: SG.redCircle(`<text x="50" y="60" font-size="30" font-weight="bold" text-anchor="middle" fill="#333">20</text><text x="50" y="76" font-size="11" text-anchor="middle" fill="#333">zone</text>`), en: "Entry to 20 mph zone", tr: "20 mph bölgesi başlangıcı" },
  { id: "s30",       cat: "order", svg: SG.redCircle(`<text x="50" y="62" font-size="36" font-weight="bold" text-anchor="middle" fill="#333">30</text>`), en: "Maximum speed 30 mph", tr: "Azami hız 30 mph" },
  { id: "snsl",      cat: "order", svg: `<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="47" fill="#fff" stroke="#bbb" stroke-width="3"/><rect x="10" y="44" width="80" height="12" fill="#333" transform="rotate(-25 50 50)"/></svg>`, en: "National speed limit applies", tr: "Ulusal hız sınırı geçerli" },
  { id: "sstop",     cat: "order", svg: SG.stop(), en: "Stop and give way", tr: "Dur ve yol ver" },
  { id: "sgiveway",  cat: "order", svg: SG.invTriangle(), en: "Give way to traffic on major road", tr: "Ana yoldaki trafiğe yol ver" },
  { id: "snoentry",  cat: "order", svg: `<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="47" fill="#c00"/><rect x="18" y="42" width="64" height="16" rx="3" fill="#fff"/></svg>`, en: "No entry for vehicular traffic", tr: "Taşıt giremez" },
  { id: "snoovertake", cat: "order", svg: SG.redCircle(SG.car(14, 32, 1.15, "#c00") + SG.car(52, 32, 1.15, "#333")), en: "No overtaking", tr: "Sollama yasak" },
  { id: "snomotor",  cat: "order", svg: SG.redCircle(`<g transform="translate(24,22) scale(0.9)"><rect x="10" y="24" width="44" height="14" rx="4" fill="#333"/><path d="M18 24 L24 14 H40 L46 24 Z" fill="#333"/><circle cx="20" cy="42" r="5" fill="#333"/><circle cx="46" cy="42" r="5" fill="#333"/></g><rect x="12" y="44" width="76" height="9" fill="#c00" transform="rotate(-45 50 50)"/>`), en: "No motor vehicles", tr: "Motorlu taşıt giremez" },
  { id: "snocycle",  cat: "order", svg: SG.redCircle(`<g transform="translate(20,30)"><circle cx="12" cy="28" r="11" fill="none" stroke="#333" stroke-width="4"/><circle cx="48" cy="28" r="11" fill="none" stroke="#333" stroke-width="4"/><path d="M12 28 L26 8 H40 L48 28 M26 8 L34 28" fill="none" stroke="#333" stroke-width="4"/></g>`), en: "No cycling", tr: "Bisiklet giremez" },
  { id: "snoright",  cat: "order", svg: SG.redCircle(`<path d="M30 62 V44 Q30 34 42 34 H56" fill="none" stroke="#333" stroke-width="9"/><path d="M52 22 L70 34 L52 46 Z" fill="#333"/><rect x="12" y="44" width="76" height="9" fill="#c00" transform="rotate(-45 50 50)"/>`), en: "No right turn", tr: "Sağa dönüş yasak" },
  { id: "snouturn",  cat: "order", svg: SG.redCircle(`<path d="M34 68 V40 Q34 26 50 26 Q66 26 66 40 V52" fill="none" stroke="#333" stroke-width="8"/><path d="M56 50 L66 66 L76 50 Z" fill="#333"/><rect x="12" y="44" width="76" height="9" fill="#c00" transform="rotate(-45 50 50)"/>`), en: "No U-turns", tr: "U dönüşü yasak" },
  { id: "snowait",   cat: "order", svg: `<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="47" fill="#0064c8" stroke="#c00" stroke-width="8"/><rect x="8" y="43" width="84" height="10" fill="#c00" transform="rotate(-45 50 50)"/></svg>`, en: "No waiting", tr: "Bekleme (park) yasak" },
  { id: "snostop",   cat: "order", svg: `<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="47" fill="#0064c8" stroke="#c00" stroke-width="8"/><rect x="8" y="43" width="84" height="10" fill="#c00" transform="rotate(-45 50 50)"/><rect x="8" y="43" width="84" height="10" fill="#c00" transform="rotate(45 50 50)"/></svg>`, en: "No stopping (Clearway)", tr: "Durmak yasak (Clearway)" },
  { id: "sahead",    cat: "order", svg: SG.blueCircle(`<path d="M50 78 V32" stroke="#fff" stroke-width="10"/><path d="M32 40 L50 16 L68 40 Z" fill="#fff"/>`), en: "Ahead only", tr: "Sadece ileri" },
  { id: "sturnleft", cat: "order", svg: SG.blueCircle(`<path d="M70 74 H44" stroke="#fff" stroke-width="10"/><path d="M52 56 L24 74 L52 92 Z" fill="#fff" transform="translate(0,-18)"/>`), en: "Turn left", tr: "Sola dön" },
  { id: "skeepleft", cat: "order", svg: SG.blueCircle(`<path d="M62 26 V50 Q62 64 48 64 H40" stroke="#fff" stroke-width="9" fill="none"/><path d="M44 50 L24 64 L44 78 Z" fill="#fff"/>`), en: "Keep left", tr: "Soldan git" },
  { id: "sminirb",   cat: "order", svg: SG.blueCircle(`<circle cx="50" cy="50" r="22" fill="none" stroke="#fff" stroke-width="9"/><path d="M50 14 L60 28 L40 28 Z" fill="#fff" transform="rotate(120 50 50)"/><path d="M50 14 L60 28 L40 28 Z" fill="#fff" transform="rotate(240 50 50)"/><path d="M50 14 L60 28 L40 28 Z" fill="#fff"/>`), en: "Mini-roundabout — give way to the right", tr: "Mini dönel kavşak — sağa yol ver" },
  { id: "sbuslane",  cat: "order", svg: SG.blueRect(`<text x="50" y="40" font-size="15" font-weight="bold" text-anchor="middle" fill="#fff">BUS</text><text x="50" y="60" font-size="15" font-weight="bold" text-anchor="middle" fill="#fff">LANE</text><path d="M20 75 H80" stroke="#fff" stroke-width="4"/>`), en: "With-flow bus lane", tr: "Otobüs şeridi" },
  { id: "soneway",   cat: "order", svg: SG.blueRect(`<path d="M50 80 V36" stroke="#fff" stroke-width="10"/><path d="M32 44 L50 18 L68 44 Z" fill="#fff"/><text x="50" y="94" font-size="11" text-anchor="middle" fill="#fff">One way</text>`), en: "One-way traffic", tr: "Tek yönlü yol" },
  { id: "wbendr",    cat: "warning", svg: SG.triangle(`<path d="M42 80 V58 Q42 46 54 46 H62" fill="none" stroke="#333" stroke-width="8"/>`), en: "Bend to right ahead", tr: "İleride sağa viraj" },
  { id: "wdouble",   cat: "warning", svg: SG.triangle(`<path d="M56 80 V68 Q56 60 48 58 Q40 56 40 48 Q40 40 48 38 H56" fill="none" stroke="#333" stroke-width="7"/>`), en: "Double bend, first to left", tr: "İleride çift viraj (önce sola)" },
  { id: "wroundab",  cat: "warning", svg: SG.triangle(`<circle cx="50" cy="60" r="13" fill="none" stroke="#333" stroke-width="6"/><path d="M50 38 L56 48 L44 48 Z" fill="#333"/><path d="M50 38 L56 48 L44 48 Z" fill="#333" transform="rotate(120 50 60)"/><path d="M50 38 L56 48 L44 48 Z" fill="#333" transform="rotate(240 50 60)"/>`), en: "Roundabout ahead", tr: "İleride dönel kavşak" },
  { id: "wnarrow",   cat: "warning", svg: SG.triangle(`<path d="M36 82 L44 50 M64 82 L56 50" stroke="#333" stroke-width="6"/>`), en: "Road narrows on both sides", tr: "Yol her iki taraftan daralıyor" },
  { id: "wtwoway",   cat: "warning", svg: SG.triangle(`<path d="M40 78 V52 M60 52 V78" stroke="#333" stroke-width="8"/><path d="M28 56 L40 38 L52 56 Z" fill="#333"/><path d="M48 74 L60 92 L72 74 Z" fill="#333" transform="translate(0,-14)"/>`), en: "Two-way traffic ahead", tr: "İleride çift yönlü trafik" },
  { id: "wsignals",  cat: "warning", svg: SG.triangle(`<rect x="42" y="40" width="16" height="40" rx="4" fill="#333"/><circle cx="50" cy="49" r="4.5" fill="#c00"/><circle cx="50" cy="60" r="4.5" fill="#fb0"/><circle cx="50" cy="71" r="4.5" fill="#0a0"/>`), en: "Traffic signals ahead", tr: "İleride trafik ışıkları" },
  { id: "wslippery", cat: "warning", svg: SG.triangle(SG.car(30, 48, 1.3, "#333") + `<path d="M26 78 q6 -5 12 0 M52 78 q6 -5 12 0" stroke="#333" stroke-width="3.5" fill="none"/>`), en: "Slippery road", tr: "Kaygan yol" },
  { id: "wsteep",    cat: "warning", svg: SG.triangle(`<path d="M18 80 L82 80 L82 56 Z" fill="#333"/><text x="34" y="74" font-size="14" font-weight="bold" fill="#fff">10%</text>`), en: "Steep hill downwards", tr: "Dik iniş" },
  { id: "wlevelbar", cat: "warning", svg: SG.triangle(`<path d="M30 44 L70 80 M30 80 L70 44" stroke="#333" stroke-width="6"/><rect x="28" y="58" width="44" height="7" fill="#333"/>`), en: "Level crossing with barrier ahead", tr: "İleride bariyerli hemzemin geçit" },
  { id: "wchildren", cat: "warning", svg: SG.triangle(`<g fill="#333"><circle cx="40" cy="46" r="5"/><path d="M34 52 L46 52 L44 70 L42 82 M38 82 L40 70" stroke="#333" stroke-width="4" fill="none"/><circle cx="60" cy="50" r="4.4"/><path d="M55 56 L65 56 L63 70 L62 80 M58 80 L59 70" stroke="#333" stroke-width="3.6" fill="none"/></g>`), en: "School — children going to or from school", tr: "Okul — çocuk geçebilir" },
  { id: "wped",      cat: "warning", svg: SG.triangle(`<circle cx="48" cy="44" r="5.4" fill="#333"/><path d="M48 50 L48 66 L42 82 M48 66 L55 82 M40 58 L56 56" stroke="#333" stroke-width="4.4" fill="none"/>`), en: "Pedestrians in road ahead", tr: "İleride yolda yayalar" },
  { id: "wzebra",    cat: "warning", svg: SG.triangle(`<circle cx="50" cy="42" r="5" fill="#333"/><path d="M50 47 L50 62 L44 80 M50 62 L57 80 M42 55 L58 53" stroke="#333" stroke-width="4" fill="none"/><path d="M28 84 H72" stroke="#333" stroke-width="3" stroke-dasharray="7 5"/>`), en: "Zebra crossing ahead", tr: "İleride yaya geçidi" },
  { id: "wcattle",   cat: "warning", svg: SG.triangle(`<g fill="#333"><ellipse cx="50" cy="62" rx="18" ry="9"/><rect x="63" y="48" width="8" height="12" rx="3"/><circle cx="69" cy="47" r="4.6"/><path d="M38 70 V82 M46 70 V82 M56 70 V82 M62 70 V82" stroke="#333" stroke-width="3.6"/></g>`), en: "Cattle on road", tr: "Yolda çiftlik hayvanı" },
  { id: "wwild",     cat: "warning", svg: SG.triangle(`<g fill="#333"><ellipse cx="50" cy="64" rx="16" ry="8"/><path d="M62 60 L70 46 M66 52 L74 50 M64 55 L72 58" stroke="#333" stroke-width="3"/><path d="M40 70 V82 M48 70 V82 M56 70 V82" stroke="#333" stroke-width="3.4"/></g>`), en: "Wild animals (deer)", tr: "Yabani hayvan (geyik)" },
  { id: "wwind",     cat: "warning", svg: SG.triangle(`<path d="M30 52 h30 M30 62 h36 M30 72 h26" stroke="#333" stroke-width="4"/><path d="M56 46 q14 6 0 12 M62 66 q12 6 0 12" stroke="#333" stroke-width="3.5" fill="none"/>`), en: "Side winds", tr: "Yandan rüzgâr" },
  { id: "whump",     cat: "warning", svg: SG.triangle(`<path d="M26 78 Q50 46 74 78 Z" fill="#333"/>`), en: "Hump bridge", tr: "Tümsek köprü" },
  { id: "wice",      cat: "warning", svg: SG.triangle(`<g stroke="#333" stroke-width="3.2"><path d="M50 42 V82 M32 52 L68 72 M68 52 L32 72"/><path d="M50 42 l-5 6 M50 42 l5 6 M50 82 l-5 -6 M50 82 l5 -6"/></g>`), en: "Risk of ice", tr: "Buzlanma riski" },
  { id: "wqueues",   cat: "warning", svg: SG.triangle(SG.car(26, 60, 0.8, "#333") + SG.car(48, 60, 0.8, "#333") + SG.car(37, 45, 0.8, "#333")), en: "Traffic queues likely ahead", tr: "İleride trafik kuyruğu olabilir" },
  { id: "wworks",    cat: "works", svg: SG.triangle(`<g fill="#333"><circle cx="46" cy="44" r="5"/><path d="M46 49 L46 64 L40 82 M46 64 L52 82 M46 52 L60 60 L68 52" stroke="#333" stroke-width="4" fill="none"/><path d="M62 52 L74 82" stroke="#333" stroke-width="3.4"/><ellipse cx="66" cy="60" rx="4" ry="2.6" transform="rotate(70 66 60)"/></g>`), en: "Road works", tr: "Yol çalışması" },
  { id: "wloose",    cat: "works", svg: SG.triangle(SG.car(28, 46, 1.2, "#333") + `<circle cx="38" cy="78" r="2.4" fill="#333"/><circle cx="50" cy="82" r="2.4" fill="#333"/><circle cx="62" cy="78" r="2.4" fill="#333"/>`), en: "Loose chippings", tr: "Gevşek mıcır" },
  { id: "imotorway", cat: "info", svg: SG.blueRect(`<path d="M50 24 V78 M32 34 Q32 60 44 74 M68 34 Q68 60 56 74" stroke="#fff" stroke-width="7" fill="none"/>`), en: "Start of motorway regulations", tr: "Otoyol başlangıcı" },
  { id: "iendmw",    cat: "info", svg: SG.blueRect(`<path d="M50 24 V78 M32 34 Q32 60 44 74 M68 34 Q68 60 56 74" stroke="#fff" stroke-width="7" fill="none"/><rect x="10" y="44" width="80" height="9" fill="#c00" transform="rotate(-45 50 50)"/>`), en: "End of motorway", tr: "Otoyol sonu" },
  { id: "inothrough", cat: "info", svg: SG.blueRect(`<path d="M50 40 V80" stroke="#fff" stroke-width="10"/><rect x="26" y="26" width="48" height="12" fill="#c00"/>`), en: "No through road for vehicles", tr: "Çıkmaz yol" },
];

/* ---------- ANİMASYONLU DERSLER ---------- */
const LESSONS = [
  { id: "l_skid", icon: "🚗💨", title: { tr: "Kayma ve Fren Kontrolü", en: "Skids & Brake Control" },
    intro: { tr: "Araç kaydığında panik yapma! Bu derste kayma anında ne yapman gerektiğini animasyonlarla öğreneceksin.",
             en: "Don't panic when the car skids! In this lesson you'll learn what to do in a skid, with animations." },
    qids: ["skid_brake", "skid_gas", "skid_steer", "aquaplane", "emergency_stop"] },

  { id: "l_weather", icon: "🌧️❄️", title: { tr: "Islak, Buzlu ve Sisli Yollar", en: "Wet, Icy & Foggy Roads" },
    intro: { tr: "Kötü havada tek kural: yavaşla ve mesafeyi aç. Ayrıntıları izleyelim.",
             en: "One rule in bad weather: slow down and open the gap. Let's see the details." },
    qids: ["wet_road", "follow_wet", "ice_grip", "follow_ice", "snow_gas", "fog_slow", "fog_lights", "winds", "high_sided", "low_sun", "glare"] },

  { id: "l_ped", icon: "🚸", title: { tr: "Yayalar ve Geçitler", en: "Pedestrians & Crossings" },
    intro: { tr: "İngiltere'de yaya kraldır! Zebra, pelikan ve okul geçitlerini öğrenelim.",
             en: "In the UK the pedestrian is king! Let's learn zebra, pelican and school crossings." },
    qids: ["zebra", "pelican_red", "pelican_amber", "patrol", "parked_veh", "icecream", "elderly", "school_bus"] },

  { id: "l_lights", icon: "🚦", title: { tr: "Işıklar ve Kavşaklar", en: "Lights & Junctions" },
    intro: { tr: "Kırmızı, sarı, yeşil… ve İngiliz usulü dönel kavşaklar: sağdan gelene yol ver!",
             en: "Red, amber, green… and British roundabouts: give way to the right!" },
    qids: ["red_light", "amber", "green_light", "lights_out", "giveway", "stopsign", "roundabout", "mini_rb"] },

  { id: "l_motorway", icon: "🛣️", title: { tr: "Otoyol Kuralları", en: "Motorway Rules" },
    intro: { tr: "70 mph, kırmızı X, emniyet şeridi ve arıza durumu — otoyolun altın kuralları.",
             en: "70 mph, the red X, the hard shoulder and breakdowns — the golden rules of the motorway." },
    qids: ["mw_speed", "mw_breakdown", "hazard_lights", "hard_shoulder", "red_x", "variable_limit", "triangle"] },

  { id: "l_vehicle", icon: "🔧", title: { tr: "Araç Bakımı ve Uyarı Işıkları", en: "Maintenance & Warning Lights" },
    intro: { tr: "Gösterge panelindeki ışıklar seninle konuşur. Hangisi 'hemen dur' diyor, öğrenelim.",
             en: "The dashboard lights talk to you. Let's learn which one says 'stop now'." },
    qids: ["oil_light", "engine_light", "brake_light", "overheat", "tyre_tread", "tyre_pressure", "spongy"] },

  { id: "l_driver", icon: "🧠", title: { tr: "Sürücü Güvenliği", en: "Driver Safety" },
    intro: { tr: "Telefon, alkol, yorgunluk… En büyük tehlike bazen direksiyondakidir.",
             en: "Phones, alcohol, tiredness… Sometimes the biggest danger is behind the wheel." },
    qids: ["mobile", "handsfree", "drink", "tired", "seatbelt", "child_seat", "tailgate", "mirrors_when", "blindspot"] },

  { id: "l_night", icon: "🌙", title: { tr: "Gece Sürüşü", en: "Night Driving" },
    intro: { tr: "Gece görüş azalır, mesafeler yanıltır. Farları doğru kullanmayı öğrenelim.",
             en: "At night vision drops and distances deceive. Let's use our lights properly." },
    qids: ["night_speed", "dazzle", "dip_lights", "ped_night", "headlight_fail"] },

  { id: "l_rules", icon: "📏", title: { tr: "Park ve Yol Kuralları", en: "Parking & Road Rules" },
    intro: { tr: "Sarı çizgiler, zigzaglar, otobüs şeritleri ve bisikletlilere 1,5 metre kuralı.",
             en: "Yellow lines, zigzags, bus lanes and the 1.5 m rule for cyclists." },
    qids: ["dbl_yellow", "sgl_yellow", "zigzag", "bus_lane", "cyclist_pass", "double_parked", "single_cw", "dual_cw"] },

  { id: "l_distance", icon: "📐", title: { tr: "Durma Mesafeleri (Ezber Şart!)", en: "Stopping Distances (Must Memorise!)" },
    intro: { tr: "Sınavın en sevdiği rakamlar: 30 mph'de 23 metre, 50'de 53, 70'te 96. Düşünme + fren = toplam durma. Hadi ezberleyelim!",
             en: "The exam's favourite numbers: 23 metres at 30 mph, 53 at 50, 96 at 70. Thinking + braking = overall stopping. Let's memorise!" },
    qids: ["thinking_dist", "stop30", "stop50", "stop70", "stopping_dist", "tailgate"] },

  { id: "l_firstaid", icon: "🚑", title: { tr: "Kaza Yerinde İlk Yardım", en: "First Aid at an Incident" },
    intro: { tr: "Umarım hiç gerekmez ama sınavda kesin sorulur: önce güvenlik, sonra 999, nefes yoksa kalp masajı, kaska dokunma!",
             en: "Hopefully never needed, but always examined: safety first, then 999, CPR if not breathing, leave the helmet on!" },
    qids: ["incident_first", "casualty_breathing", "helmet", "mot", "insurance"] },

  { id: "l_signs", icon: "🪧", title: { tr: "Levha Okuma Sanatı", en: "The Art of Reading Signs" },
    intro: { tr: "Şekli gör, anlamını bil! Kırmızı çember yasak der, üçgen uyarır, mavi daire talimat verir. Bu kodu çözersen hiç görmediğin levhayı bile okursun.",
             en: "See the shape, know the meaning! Red circles prohibit, triangles warn, blue circles instruct. Crack this code and you can read signs you've never seen." },
    qids: ["sign_redcircle", "sign_triangle", "sign_bluecircle", "sign_octagon", "sign_motorwayblue", "sign_brown"] },

  { id: "l_country", icon: "🌳", title: { tr: "Kırsal Yollar ve Hemzemin Geçitler", en: "Country Roads & Level Crossings" },
    intro: { tr: "Virajın arkasında ne var bilemezsin: hayvan, traktör, dar köprü… Ve asla bariyerin etrafından dolaşma!",
             en: "You never know what's past the bend: animals, tractors, narrow bridges… And never zig-zag the barriers!" },
    qids: ["country_road", "sharp_bend", "concealed_bend", "narrow_road", "animals", "meeting", "narrow_bridge", "ped_rural", "level_lights", "level_barrier"] },
];

/* ---------- LEVHA SORULARI — ana quiz ve sınava karışır ---------- */
(function addSignQuestions() {
  const pick = ["sstop", "sgiveway", "snoentry", "snoovertake", "snsl", "sminirb", "wslippery", "wtwoway", "wnarrow", "wice", "wlevelbar", "wzebra", "snowait", "snostop", "iendmw", "inothrough"];
  for (const id of pick) {
    const s = SIGNS.find((x) => x.id === id);
    if (!s) continue;
    QUESTIONS.push({
      id: "sq_" + id, cat: "rules", scene: "signshape", type: "fact",
      ezber: "Shape + colour = meaning", signId: id,
      q: { en: "What does this sign mean?", tr: "Bu levha ne anlama geliyor?" },
      a: { en: s.en, tr: s.tr },
      logic: { tr: "Şekli ve rengi oku: kırmızı çember yasak, üçgen uyarı, mavi talimat.",
               en: "Read shape and colour: red circle = prohibition, triangle = warning, blue = instruction." },
      w: null, signWrongs: true,
    });
  }
})();

/* ---------- ARAYÜZ METİNLERİ ---------- */
const UI = {
  appName:      { tr: "Ehliyet Kankam UK", en: "Ehliyet Kankam UK" },
  tagline:      { tr: "İngiltere Teori Sınavı — Türkçe anlatımlı, animasyonlu", en: "UK Theory Test — with Turkish support & animations" },
  home:         { tr: "Ana Sayfa", en: "Home" },
  lessons:      { tr: "Dersler", en: "Lessons" },
  lessonsSub:   { tr: "Çizgi film gibi animasyonlu anlatım", en: "Cartoon-style animated lessons" },
  cards:        { tr: "Kartlar", en: "Flashcards" },
  cardsSub:     { tr: "100 hızlı ezber kartı", en: "100 quick memory cards" },
  quiz:         { tr: "Quiz", en: "Quiz" },
  quizSub:      { tr: "Yanlışta animasyon devreye girer", en: "Animation plays when you're wrong" },
  mock:         { tr: "Deneme Sınavı", en: "Mock Test" },
  mockSub:      { tr: "50 soru • 57 dakika • 43 doğru = geçtin", en: "50 questions • 57 min • pass at 43" },
  mistakes:     { tr: "Yanlışlarım", en: "My Mistakes" },
  mistakesSub:  { tr: "Yanlış yaptıklarını animasyonla tekrar et", en: "Retry your mistakes with animations" },
  noMistakes:   { tr: "Hiç yanlışın yok! Önce quiz veya sınav çöz 🎉", en: "No mistakes yet! Try a quiz or mock test first 🎉" },
  narrate:      { tr: "🔊 Bu adımı anlat (TR+EN)", en: "🔊 Narrate this step (TR+EN)" },
  signs:        { tr: "Levhalar", en: "Signs" },
  signsSub:     { tr: "Highway Code trafik işaretleri", en: "Highway Code traffic signs" },
  progress:     { tr: "İlerlemen", en: "Your progress" },
  chooseCat:    { tr: "Konu seç", en: "Choose a topic" },
  allCats:      { tr: "Tüm Konular", en: "All Topics" },
  start:        { tr: "Başla", en: "Start" },
  next:         { tr: "İleri", en: "Next" },
  prev:         { tr: "Geri", en: "Back" },
  check:        { tr: "Kontrol Et", en: "Check" },
  correct:      { tr: "DOĞRU! Aferin! 🎉", en: "CORRECT! Well done! 🎉" },
  wrong:        { tr: "Yanlış — gel, animasyonla öğrenelim 👇", en: "Wrong — let's learn it with the animation 👇" },
  theAnswer:    { tr: "Doğru cevap", en: "Correct answer" },
  inEnglish:    { tr: "İngilizce şöyle diyor", en: "In English it says" },
  inTurkish:    { tr: "Türkçesi", en: "In Turkish" },
  logic:        { tr: "Mantığı", en: "The logic" },
  mnemonic:     { tr: "Ezber kodu", en: "Memory hook" },
  continueBtn:  { tr: "Devam", en: "Continue" },
  showAnim:     { tr: "🎬 Animasyonla anlat", en: "🎬 Explain with animation" },
  flip:         { tr: "Kartı çevir", en: "Flip card" },
  knew:         { tr: "✅ Biliyordum", en: "✅ I knew it" },
  didntKnow:    { tr: "❌ Bilmiyordum", en: "❌ I didn't know" },
  score:        { tr: "Skor", en: "Score" },
  question:     { tr: "Soru", en: "Question" },
  finish:       { tr: "Bitir", en: "Finish" },
  timeLeft:     { tr: "Kalan süre", en: "Time left" },
  passed:       { tr: "GEÇTİN! 🎉🎉 Tebrikler!", en: "PASSED! 🎉🎉 Congratulations!" },
  failed:       { tr: "Bu sefer olmadı — çalışmaya devam! 💪", en: "Not this time — keep studying! 💪" },
  passmark:     { tr: "Geçme notu: 43/50", en: "Pass mark: 43/50" },
  reviewWrong:  { tr: "Yanlışlarını animasyonla gör", en: "Review your mistakes with animations" },
  playAll:     { tr: "▶ Otomatik oynat", en: "▶ Autoplay" },
  stopAuto:    { tr: "⏸ Durdur", en: "⏸ Pause" },
  listen:      { tr: "🔊 Dinle", en: "🔊 Listen" },
  listenEN:    { tr: "🔊 İngilizce dinle", en: "🔊 Listen in English" },
  listenTR:    { tr: "🔊 Türkçe dinle", en: "🔊 Listen in Turkish" },
  whatHappens: { tr: "Ne oluyor?", en: "What's happening?" },
  step:        { tr: "Adım", en: "Step" },
  lessonDone:  { tr: "Ders bitti! 🎓", en: "Lesson complete! 🎓" },
  backHome:    { tr: "Ana sayfaya dön", en: "Back to home" },
  tryAgain:    { tr: "Tekrar dene", en: "Try again" },
  signQuiz:    { tr: "Levha Quizi", en: "Sign Quiz" },
  whichSign:   { tr: "Bu levha ne anlama geliyor?", en: "What does this sign mean?" },
  browse:      { tr: "İncele", en: "Browse" },
  catOrder:    { tr: "Emir / Yasak Levhaları", en: "Signs Giving Orders" },
  catWarning:  { tr: "Uyarı Levhaları", en: "Warning Signs" },
  catWorks:    { tr: "Yol Çalışması", en: "Road Works" },
  catInfo:     { tr: "Bilgi Levhaları", en: "Information Signs" },
  statSeen:    { tr: "görülen soru", en: "questions seen" },
  statCorrect: { tr: "doğruluk", en: "accuracy" },
  statBest:    { tr: "en iyi deneme", en: "best mock" },
  langBtn:     { tr: "EN", en: "TR" },
  qLangLabel:  { tr: "Soru dili", en: "Question language" },
  both:        { tr: "İkisi", en: "Both" },
  nonCommercial: { tr: "Kişisel kullanım içindir • ticari değildir ❤️", en: "Personal use only • non-commercial ❤️" },
  installHint: { tr: "📱 Telefona kurmak için: tarayıcı menüsü → “Ana Ekrana Ekle”", en: "📱 To install: browser menu → “Add to Home Screen”" },
  guide:       { tr: "Sınav Günü Rehberi", en: "Exam Day Guide" },
  guideSub:    { tr: "Format, hazard perception, ipuçları", en: "Format, hazard perception, tips" },
  glossary:    { tr: "Sözlük", en: "Glossary" },
  glossarySub: { tr: "Sınav kelimeleri: İngilizce → Türkçe, sesli", en: "Exam vocabulary: EN → TR, with audio" },
  searchPh:    { tr: "Kelime ara… (ör. skid, kavşak)", en: "Search… (e.g. skid, junction)" },
  noResult:    { tr: "Sonuç yok — başka bir kelime dene", en: "No results — try another word" },
  backupTitle: { tr: "İlerleme yedeği", en: "Progress backup" },
  copyBackup:  { tr: "📤 Yedek kodu al", en: "📤 Get backup code" },
  pasteBackup: { tr: "📥 Yedek yükle", en: "📥 Load backup" },
  resetProg:   { tr: "🗑️ Sıfırla", en: "🗑️ Reset" },
  copied:      { tr: "Kod kopyalandı! Diğer telefonda 'Yedek yükle'ye yapıştır.", en: "Code copied! Paste it via 'Load backup' on the other phone." },
  showCode:    { tr: "Bu kodu kopyala ve diğer cihazda 'Yedek yükle'ye yapıştır:", en: "Copy this code and paste it via 'Load backup' on the other device:" },
  pastePrompt: { tr: "Yedek kodunu buraya yapıştır:", en: "Paste your backup code here:" },
  loadedOk:    { tr: "Yedek yüklendi! 🎉", en: "Backup loaded! 🎉" },
  badBackup:   { tr: "Kod çözülemedi — tam kopyaladığından emin ol.", en: "Couldn't read the code — make sure you copied all of it." },
  confirmReset: { tr: "Tüm ilerleme silinsin mi? (skorlar, yanlışlar, dersler)", en: "Delete all progress? (scores, mistakes, lessons)" },
  profiles:     { tr: "Profiller", en: "Profiles" },
  whoTitle:     { tr: "Kim çalışıyor? 👋", en: "Who's studying? 👋" },
  whoSub:       { tr: "Herkesin ilerlemesi ayrı tutulur — skorlar birbirine karışmaz.", en: "Everyone's progress is kept separate — scores never mix." },
  namePh:       { tr: "İsmini yaz…", en: "Type your name…" },
  createProfile: { tr: "Profili oluştur", en: "Create profile" },
  addProfile:   { tr: "➕ Yeni profil ekle", en: "➕ Add new profile" },
  activeLabel:  { tr: "aktif", en: "active" },
  confirmDelete: { tr: "Bu profil ve tüm ilerlemesi silinsin mi?", en: "Delete this profile and all its progress?" },
  trVoiceMissing: { tr: "📢 Telefonda Türkçe ses yüklü değil. Ayarlar → Erişilebilirlik → Seslendirme'den Türkçe ses indirirsen sesli anlatım Türkçe de çalışır.", en: "📢 No Turkish voice installed. Add one in Settings → Accessibility → Spoken Content for Turkish narration." },
  voiceSettings: { tr: "🔊 Ses Ayarları", en: "🔊 Voice Settings" },
  voiceIntro:   { tr: "Beğenmediğin sesi burada değiştir ve 'Dene' ile dinle.", en: "Change the voice here and preview with 'Test'." },
  voiceFixTitle: { tr: "🎧 Ses robotik mi geliyor? 2 dakikada düzelt:", en: "🎧 Voice sounds robotic? Fix in 2 minutes:" },
  voiceFixIOS:  { tr: "iPhone/iPad: Ayarlar → Erişilebilirlik → Sesli İçerik → Sesler → Türkçe → Yelda → yanındaki ☁️ simgesine dokunup 'Geliştirilmiş' (Enhanced) sesi indir. Sonra Sesler → İngilizce (UK) → Sonia veya Daniel 'Enhanced' indir. Buraya dönüp o sesleri seç — fark gece gündüz!", en: "iPhone/iPad: Settings → Accessibility → Spoken Content → Voices → Turkish → Yelda → tap ☁️ to download the Enhanced voice. Then Voices → English (UK) → download Sonia or Daniel Enhanced. Come back and select them here." },
  voiceFixAnd:  { tr: "Android: Play Store'dan 'Konuşma Hizmetleri (Speech Recognition & Synthesis)' uygulamasını güncelle; Ayarlar → Sistem → Diller → Metin okuma → Google motorunu seç. Türkçe ve İngiltere İngilizcesi sesleri otomatik kaliteli gelir.", en: "Android: update 'Speech Recognition & Synthesis' from Play Store; Settings → System → Languages → Text-to-speech → choose the Google engine." },
  compactWarn:  { tr: "⚠️ Telefonun şu an DÜŞÜK kaliteli (compact) sesi kullanıyor — yukarıdaki 2 dakikalık adımla gerçek insan sesine geçebilirsin.", en: "⚠️ Your phone is using the LOW-quality (compact) voice — follow the 2-minute steps above for the natural one." },
  voiceEN:      { tr: "İngilizce ses", en: "English voice" },
  voiceTR:      { tr: "Türkçe ses", en: "Turkish voice" },
  voiceAuto:    { tr: "⭐ Otomatik (önerilen)", en: "⭐ Automatic (recommended)" },
  voiceTest:    { tr: "▶ Dene", en: "▶ Test" },
  voiceSpeed:   { tr: "Konuşma hızı", en: "Speech rate" },
  vsSlow:       { tr: "🐢 Yavaş", en: "🐢 Slow" },
  vsNormal:     { tr: "Normal", en: "Normal" },
  vsFast:       { tr: "🐇 Hızlı", en: "🐇 Fast" },
  noVoices:     { tr: "Bu cihazda hiç ses bulunamadı — sesli anlatım kapalı çalışır.", en: "No voices found on this device — narration will be silent." },
  muteOn:       { tr: "🔇 Sesli anlatımı KAPAT", en: "🔇 Turn narration OFF" },
  muteOff:      { tr: "🔊 Sesli anlatımı AÇ", en: "🔊 Turn narration ON" },
  mutedNow:     { tr: "Sesli anlatım kapatıldı — istediğinde Ses Ayarları'ndan açabilirsin.", en: "Narration is off — re-enable anytime in Voice Settings." },
  lockTitle:    { tr: "🔒 Giriş Kodu", en: "🔒 Access Code" },
  lockSub:      { tr: "Bu uygulama özeldir. Devam etmek için giriş kodunu yaz. (Kod bir kez girilir, cihaz hatırlar.)", en: "This app is private. Enter the access code to continue. (Asked once per device.)" },
  lockPh:       { tr: "Giriş kodu…", en: "Access code…" },
  lockBtn:      { tr: "Aç 🔓", en: "Unlock 🔓" },
  lockWrong:    { tr: "Kod yanlış — tekrar dene", en: "Wrong code — try again" },
  installTitle: { tr: "Cihaza Kur", en: "Install App" },
  installSub:   { tr: "Telefon • tablet • bilgisayar — uygulama olarak", en: "Phone • tablet • PC — as a real app" },
  installNow:   { tr: "📥 Şimdi kur", en: "📥 Install now" },
  installed:    { tr: "Uygulama kuruldu!", en: "App installed!" },
  installIntro: { tr: "Bu uygulama PWA teknolojisiyle yapıldı: mağaza gerekmeden telefona, tablete ve bilgisayara gerçek uygulama gibi kurulur, kendi simgesiyle açılır, internetsiz çalışır.", en: "This app is a PWA: it installs like a real app on phones, tablets and PCs — no app store needed, its own icon, works offline." },
  instAndroid:  { tr: "Chrome menüsü (⋮) → “Uygulamayı yükle” veya “Ana ekrana ekle”. Simge ana ekrana gelir, tam ekran açılır.", en: "Chrome menu (⋮) → “Install app” or “Add to Home screen”." },
  instIOS:      { tr: "Safari'de Paylaş düğmesi (kare+ok) → aşağı kaydır → “Ana Ekrana Ekle” → Ekle. Simge ana ekrana gelir.", en: "In Safari: Share button → “Add to Home Screen” → Add." },
  instPC:       { tr: "Chrome/Edge adres çubuğunun sağındaki kurulum simgesine (⊕/💻) tıkla → “Yükle”. Masaüstü simgesi oluşur.", en: "Click the install icon at the right of the address bar in Chrome/Edge → “Install”." },
  instNote:     { tr: "Not: Kurulum seçeneğinin çıkması için uygulamayı kalıcı web adresinden açmalısın (GitHub Pages — kurulumu README'de 3 adımda anlatılıyor). Kalıcı adres bir kez ayarlandıktan sonra herkes oradan kurabilir.", en: "Note: to get the install option, open the app from its permanent web address (GitHub Pages — 3 steps in the README). Once set up, everyone can install from there." },
};

/* ---------- SINAV SÖZLÜĞÜ — İngilizce terim → Türkçe karşılık ---------- */
const GLOSSARY = [
  ["accelerator", "gaz pedalı"], ["aquaplaning", "su üstünde kayma"], ["amber light", "sarı ışık"],
  ["bend", "viraj"], ["blind spot", "kör nokta"], ["brake", "fren"], ["braking distance", "fren mesafesi"],
  ["breakdown", "arıza"], ["built-up area", "meskûn mahal / yerleşim alanı"],
  ["carriageway", "taşıt yolu"], ["casualty", "kazazede / yaralı"], ["child seat", "çocuk koltuğu"],
  ["clutch", "debriyaj"], ["congestion", "trafik sıkışıklığı"], ["coolant", "motor soğutma suyu"],
  ["crossroads", "dört yol ağzı"], ["cyclist", "bisikletli"],
  ["dazzle", "far/ışık göz alması"], ["dipped headlights", "kısa farlar"], ["diversion", "servis yolu / sapma"],
  ["documents", "belgeler"], ["dual carriageway", "bölünmüş yol"],
  ["engine", "motor"], ["emergency stop", "acil duruş"], ["emergency vehicle", "acil durum aracı"],
  ["fatigue / tiredness", "yorgunluk"], ["fine / penalty", "para cezası"], ["fog lights", "sis lambaları"],
  ["full beam", "uzun farlar"],
  ["gear", "vites"], ["give way", "yol ver"], ["gradient", "eğim / yokuş"], ["grip", "yol tutuşu"],
  ["handbrake", "el freni"], ["hands-free", "eller serbest (telefon)"], ["hard shoulder", "emniyet şeridi"],
  ["hazard", "tehlike"], ["hazard warning lights", "dörtlü ikaz lambaları"], ["headlights", "farlar"],
  ["hill start", "yokuşta kalkış"], ["horn", "korna"],
  ["indicator / signal", "sinyal"], ["insurance", "sigorta"],
  ["junction", "kavşak"],
  ["kerb", "kaldırım kenar taşı"],
  ["lane", "şerit"], ["level crossing", "hemzemin geçit (tren)"], ["lorry", "kamyon / tır"],
  ["mirror", "ayna"], ["MOT test", "araç muayenesi"], ["motorway", "otoyol"],
  ["national speed limit", "ulusal hız sınırı"],
  ["oil level", "yağ seviyesi"], ["oncoming traffic", "karşıdan gelen trafik"], ["one-way street", "tek yönlü yol"],
  ["overtaking", "sollama / öndekini geçme"],
  ["pavement", "kaldırım"], ["pedestrian", "yaya"], ["pedestrian crossing", "yaya geçidi"],
  ["pelican crossing", "pelikan geçidi (ışıklı yaya geçidi)"], ["penalty points", "ceza puanı"],
  ["priority", "geçiş önceliği"], ["provisional licence", "geçici (öğrenci) ehliyet"], ["puffin crossing", "puffin geçidi (sensörlü)"],
  ["red light", "kırmızı ışık"], ["reversing", "geri geri gitme"], ["road works", "yol çalışması"],
  ["roundabout", "dönel kavşak (göbek)"],
  ["seat belt", "emniyet kemeri"], ["single carriageway", "bölünmemiş (tek platform) yol"],
  ["skid", "kayma / patinaj"], ["slip road", "bağlantı (katılım) yolu"], ["speed camera", "hız kamerası"],
  ["speed limit", "hız sınırı"], ["steering wheel", "direksiyon"], ["stopping distance", "durma mesafesi"],
  ["tailgating", "öndekini çok yakın takip"], ["thinking distance", "düşünme (tepki) mesafesi"],
  ["toucan crossing", "toucan geçidi (yaya+bisiklet)"], ["traffic lights", "trafik ışıkları"],
  ["tread depth", "lastik diş derinliği"], ["tyre", "lastik"], ["tyre pressure", "lastik basıncı"],
  ["verge", "yol kenarı (banket)"], ["visibility", "görüş (mesafesi)"],
  ["warning triangle", "uyarı üçgeni / reflektör"], ["windscreen", "ön cam"],
  ["zebra crossing", "zebra (çizgili) yaya geçidi"], ["zigzag lines", "zigzag çizgiler (durma yasağı)"],
];

/* ---------- SINAV GÜNÜ REHBERİ ---------- */
const GUIDE = [
  { icon: "📋", scene: "generic",
    title: { tr: "Sınav iki bölümden oluşur", en: "The test has two parts" },
    tr: "1) Çoktan seçmeli: 50 soru, 57 dakika, geçmek için 43 doğru gerekir. 2) Hazard Perception (tehlike algılama): video izleyip tehlikeyi görünce tıklarsın. İkisini de aynı gün, aynı oturumda geçmen gerekir.",
    en: "1) Multiple choice: 50 questions, 57 minutes, you need 43 correct to pass. 2) Hazard perception: you watch video clips and click when you see a hazard. You must pass both in the same sitting." },
  { icon: "🎯", scene: "distance",
    title: { tr: "Hazard Perception nasıl çalışır?", en: "How does hazard perception work?" },
    tr: "14 video klip izlersin; 15 gelişen tehlike vardır (bir klipte iki tane olur). Tehlike gelişmeye başladığı anda tıkla — erken ya da geç tıklarsan az puan alırsın. 75 üzerinden 44 puan gerekir. Sürekli ritmik tıklarsan o klipten sıfır alırsın!",
    en: "You watch 14 clips with 15 developing hazards (one clip has two). Click as soon as the hazard starts developing — too early or too late scores less. You need 44 out of 75. Clicking in a rhythm scores zero for that clip!" },
  { icon: "🇬🇧", scene: "phone",
    title: { tr: "Sınav İngilizce — ama hazırsın!", en: "The test is in English — but you're ready!" },
    tr: "Sorulardaki anahtar kelimeleri tanı: skid (kayma), give way (yol ver), pedestrian (yaya), junction (kavşak), overtake (sollama). Bu uygulamada İngilizcesini hep duyduğun için sınavda kelimeler tanıdık gelecek.",
    en: "Recognise the key words: skid, give way, pedestrian, junction, overtake. Because you always heard the English in this app, the words will feel familiar in the exam." },
  { icon: "🛡️", scene: "generic",
    title: { tr: "Altın kural", en: "The golden rule" },
    tr: "İki cevap arasında kaldıysan HER ZAMAN en güvenli, en yavaş, en sabırlı seçeneği işaretle. Theory test asla 'hızlan', 'korna çal', 'riski göze al' cevabını doğru yapmaz.",
    en: "If you're stuck between two answers, ALWAYS pick the safest, slowest, most patient option. The theory test never rewards 'speed up', 'sound your horn' or 'take the risk'." },
  { icon: "🚩", scene: "mirrors",
    title: { tr: "Soru işaretleme taktiği", en: "The flag tactic" },
    tr: "Emin olmadığın soruyu 'flag' (işaretle) ile işaretleyip geç; sonunda dönebilirsin. 57 dakika 50 soru için boldur — acele etme, soruyu iki kez oku.",
    en: "Flag any question you're unsure about and move on; you can return at the end. 57 minutes is plenty for 50 questions — don't rush, read each question twice." },
  { icon: "🪪", scene: "belt",
    title: { tr: "Yanında ne götüreceksin?", en: "What to bring?" },
    tr: "Geçerli (provisional) ehliyetini götürmeyi unutma — yoksa sınava giremezsin ve ücret yanar. Erken git, telefonunu dolaba kilitleyeceksin.",
    en: "Bring your provisional licence — without it you can't sit the test and lose the fee. Arrive early; phones are locked away." },
];
